name: sine_slider
description: Sine slider made with Flutter inspired by Arc Browser
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tactile_feedback:
    git: 
      url: https://github.com/ksokolovskyi/tactile_feedback

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1

flutter:
  uses-material-design: true
